nosetests_args = ARGUMENTS.get("args", "")

Import("test_env", "backnocles_prog")

endtoend_env = test_env.Clone()

endtoend_env["E2E_DIR"] = Dir(".")
endtoend_env["NOSETESTS_CFG"] = File("nose.cfg").srcnode()
endtoend_env["NOSETESTS_ARGS"] = nosetests_args
endtoend_env["ENV"]["SERVER_PROG"] = str(backnocles_prog)

e2e_prog = endtoend_env.Command("dummy", [],
            "nosetests --config=$NOSETESTS_CFG --where=$E2E_DIR $NOSETESTS_ARGS")
endtoend_env.Depends(e2e_prog, backnocles_prog)
# do not execute E2E tests by default
Ignore(".", e2e_prog)
alias = endtoend_env.Alias("run_e2e_tests", e2e_prog)
