language: cpp
os: linux
sudo: false
env:
  global:
    - SCONSFLAGS="--no-cache -j2"
    - CONAN_CPU_COUNT=2
    - PATH=$HOME/.local/bin:$PATH
matrix:
  include:
    - addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - g++-7
      env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # TODO install libc++
    #- addons:
    #-   apt:
    #-     sources:
    #-       - llvm-toolchain-trusty-5.0
    #-     packages:
    #-       - python3
    #-       - python3-pip
    #-       - clang-5.0
    #- env: MATRIX_EVAL="CC=clang-5.0 && CXX=clang-5.0"
before_script:
  - eval "${MATRIX_EVAL}"
  - ./tools/setup_travis_ci.sh
script:
  - ./tools/run_all_tests.sh
