Import("src_env")

MAIN = "main.cpp"
SRC = Glob("*.cpp")
# separate main.cpp
SRC = [s for s in SRC if s.get_path() != MAIN]

OUT = "backnocles"

backnocles_lib = src_env.StaticLibrary(OUT, SRC)

src_env.AppendUnique(
        LIBS=[
            backnocles_lib
        ])

backnocles_prog = src_env.Program(OUT, [MAIN])[0]

Export("backnocles_lib", "backnocles_prog")
